export const getMockSkills = async () => [
  { name: "C#", type: "Languages", regex: "c#(.net)?" },
  { name: "Java", type: "Languages", regex: "java(?! script)" },
  { name: "SQL", type: "Languages", regex: "sql(?! server)" },
  {
    name: "VB",
    type: "Languages",
    regex: "(vb|visual basic)(?! (.net|script|a))",
  },
  { name: "VB.NET", type: "Languages", regex: "(vb|visual basic).net" },
  { name: "JavaScript", type: "Languages", regex: "java script" },
  { name: "HTML", type: "Languages", regex: "html" },
  { name: "CSS", type: "Languages", regex: "css" },
  { name: "PHP", type: "Languages", regex: "php" },
  { name: "Scala", type: "Languages", regex: "scala\\b" },
  { name: "C++", type: "Languages", regex: "c \\+\\+" },
  { name: "Python", type: "Languages", regex: "python" },
  { name: "Perl", type: "Languages", regex: "perl" },
  { name: "VBA", type: "Languages", regex: "vba" },
  { name: "PL/SQL", type: "Languages", regex: "pl (\\/|\\*|\\-)? sql" },
  { name: "Swift", type: "Languages", regex: "swift" },
  { name: "C", type: "Languages", regex: "c(?!\\+|#)\\b" },
  { name: "Ada", type: "Languages", regex: "ada\\b" },
  { name: "CICS", type: "Languages", regex: "cics" },
  { name: "COBOL", type: "Languages", regex: "cobol" },
  { name: "DHTML", type: "Languages", regex: "dhtml" },
  { name: "F#", type: "Languages", regex: "f#" },
  { name: "FORTRAN", type: "Languages", regex: "fortran" },
  { name: "J#", type: "Languages", regex: "j#" },
  { name: "JCL", type: "Languages", regex: "jcl" },
  { name: "LISP", type: "Languages", regex: "lisp" },
  { name: "PowerShell", type: "Languages", regex: "power shell" },
  { name: "Pro*C", type: "Languages", regex: "pro (\\*)? c\\b" },
  { name: "RPG", type: "Languages", regex: "rpg" },
  { name: "Ruby", type: "Languages", regex: "ruby" },
  { name: "UML", type: "Languages", regex: "uml" },
  { name: "VBScript", type: "Languages", regex: "vb script" },
  { name: "XML", type: "Languages", regex: "xml" },
  { name: "BTEQ", type: "Languages", regex: "bteq" },
  { name: "AngularJS", type: "Web/Middleware", regex: "angular(.js)?" },
  { name: "Entity", type: "Web/Middleware", regex: "entity" },
  { name: "Identity", type: "Web/Middleware", regex: "identity" },
  { name: "MVC", type: "Web/Middleware", regex: "mvc" },
  { name: "WebForms", type: "Web/Middleware", regex: "web forms" },
  { name: "Bootstrap", type: "Web/Middleware", regex: "boot strap" },
  { name: "ASP.NET", type: "Web/Middleware", regex: "asp(.net)?" },
  { name: "ReactJS", type: "Web/Middleware", regex: "react(.?js| js)" },
  { name: "WPF", type: "Web/Middleware", regex: "wpf" },
  { name: "Cordova", type: "Web/Middleware", regex: "cordova" },
  { name: "Apache", type: "Web/Middleware", regex: "apache(?! spark)" },
  { name: "Tomcat", type: "Web/Middleware", regex: "tomcat" },
  { name: "ADO.NET", type: "Web/Middleware", regex: "ado(.net)?" },
  {
    name: "WinForms",
    type: "Web/Middleware",
    regex: "(winforms|windows forms)",
  },
  { name: "ColdFusion", type: "Web/Middleware", regex: "cold fusion" },
  { name: "Hibernate", type: "Web/Middleware", regex: "hibernate" },
  { name: "WebSphere", type: "Web/Middleware", regex: "web sphere" },
  {
    name: "IIS",
    type: "Web/Middleware",
    regex: "(iis|internet information services)",
  },
  { name: "jQuery", type: "Web/Middleware", regex: "j query" },
  { name: "KnockoutJS", type: "Web/Middleware", regex: "knockout(.js)?" },
  { name: "J2EE", type: "Web/Middleware", regex: "j2ee" },
  { name: "WCF", type: "Web/Middleware", regex: "wcf" },
  { name: "JSP", type: "Web/Middleware", regex: "jsp" },
  { name: "Servlets", type: "Web/Middleware", regex: "servlets" },
  { name: "JBoss", type: "Web/Middleware", regex: "jboss" },
  { name: "Jetty", type: "Web/Middleware", regex: "jetty" },
  { name: "JAXP", type: "Web/Middleware", regex: "jaxp" },
  { name: "JAXB", type: "Web/Middleware", regex: "jaxb" },
  { name: "EJB", type: "Web/Middleware", regex: "ejb" },
  { name: "JRun", type: "Web/Middleware", regex: "jrun" },
  { name: "JSF", type: "Web/Middleware", regex: "jsf" },
  { name: "Web API", type: "Web/Middleware", regex: "web api" },
  { name: "Lotus Domino", type: "Web/Middleware", regex: "lotus domino" },
  { name: "Weblogic", type: "Web/Middleware", regex: "web logic" },
  { name: "NodeJS", type: "Web/Middleware", regex: "node(.js)?" },
  { name: "SOAP", type: "Web/Middleware", regex: "soap (?! ui)" },
  { name: "Spring", type: "Web/Middleware", regex: "Spring" },
  { name: "Spring MVC", type: "Web/Middleware", regex: "spring mvc" },
  { name: "Struts", type: "Web/Middleware", regex: "struts" },
  { name: "Web Services", type: "Web/Middleware", regex: "web services" },
  { name: "AJAX", type: "Web/Middleware", regex: "ajax" },
  { name: "JSON", type: "Web/Middleware", regex: "json" },
  { name: "Windows", type: "Operating Systems", regex: "windows(?! forms)" },
  { name: "Linux", type: "Operating Systems", regex: "(linux|ubuntu|red hat)" },
  { name: "Ubuntu", type: "Operating Systems", regex: "ubuntu" },
  { name: "Red Hat", type: "Operating Systems", regex: "red hat" },
  { name: "UNIX", type: "Operating Systems", regex: "unix(?! aix|solaris)" },
  { name: "UNIX Solaris", type: "Operating Systems", regex: "unix solaris" },
  { name: "MacOS", type: "Operating Systems", regex: "macos" },
  { name: "UNIX AIX", type: "Operating Systems", regex: "unix aix|aix" },
  {
    name: "Windows Server",
    type: "Operating Systems",
    regex: "windows server",
  },
  { name: "VMware", type: "Operating Systems", regex: "vmware" },
  { name: "iOS", type: "Operating Systems", regex: "ios\\b" },
  { name: "Android", type: "Operating Systems", regex: "android" },
  { name: "Hadoop", type: "Big Data", regex: "hadoop" },
  { name: "Sqoop", type: "Big Data", regex: "sqoop" },
  { name: "Flume", type: "Big Data", regex: "flume" },
  { name: "Zookeeper", type: "Big Data", regex: "zookeeper" },
  { name: "Oozie", type: "Big Data", regex: "oozie" },
  { name: "Cloudera", type: "Big Data", regex: "cloudera" },
  {
    name: "HDFS",
    type: "Big Data",
    regex: "(hdfs | hadoop distributed file system)",
  },
  { name: "MapReduce", type: "Big Data", regex: "map reduce" },
  { name: "NiFi", type: "Big Data", regex: "nifi" },
  { name: "Hive", type: "Big Data", regex: "hive" },
  { name: "Apache Spark", type: "Big Data", regex: "apache spark" },
  { name: "Pig", type: "Big Data", regex: "pig\\b" },
  { name: "Kafka", type: "Big Data", regex: "kafka" },
  { name: "SQL Server", type: "Databases", regex: "sql server" },
  { name: "Oracle", type: "Databases", regex: "oracle" },
  { name: "Teradata", type: "Databases", regex: "teradata" },
  { name: "DB2", type: "Databases", regex: "db2" },
  { name: "Access", type: "Databases", regex: "access" },
  { name: "MySQL", type: "Databases", regex: "mysql" },
  { name: "PostreSQL", type: "Databases", regex: "postgresql" },
  { name: "MariaDB", type: "Databases", regex: "maria db" },
  { name: "MongoDB", type: "Databases", regex: "mongo db" },
  { name: "CouchDB", type: "Databases", regex: "couch db" },
  { name: "Neo4j", type: "Databases", regex: "neo 4j" },
  { name: "Ingres", type: "Databases", regex: "ingres" },
  { name: "Informix", type: "Databases", regex: "informix" },
  { name: "MonetDB", type: "Databases", regex: "monet db" },
  { name: "Netezza", type: "Databases", regex: "netezza" },
  { name: "NexusDB", type: "Databases", regex: "nexus db" },
  { name: "SAP HANA", type: "Databases", regex: "hana\\b" },
  { name: "NoSQL", type: "Databases", regex: "no sql" },
  { name: "Sybase", type: "Databases", regex: "sybase" },
  { name: "HBase", type: "Databases", regex: "hbase" },
  { name: "Cassandra", type: "Databases", regex: "cassandra" },
  {
    name: "Active Directory",
    type: "Tools",
    regex: "(active directory|(ad\\b))",
  },
  { name: "Informatica", type: "Tools", regex: "informatica" },
  { name: "SharePoint", type: "Tools", regex: "share point" },
  { name: "Pentaho", type: "Tools", regex: "pentaho" },
  { name: "SQL*Loader", type: "Tools", regex: "sql\\*loader" },
  { name: "Adobe Acrobat", type: "Tools", regex: "acrobat" },
  { name: "Dreamweaver", type: "Tools", regex: "dreamweaver" },
  { name: "Flash", type: "Tools", regex: "flash" },
  { name: "Adobe Illustrator", type: "Tools", regex: "illustrator" },
  { name: "Adobe Photoshop", type: "Tools", regex: "photoshop" },
  { name: "Agile", type: "Tools", regex: "agile\\b" },
  { name: "Ant", type: "Tools", regex: "ant\\b" },
  { name: "Casper", type: "Tools", regex: "casper" },
  { name: "ClearCase", type: "Tools", regex: "clear case" },
  { name: "DOM", type: "Tools", regex: "dom\\b" },
  { name: "Erwin", type: "Tools", regex: "erwin" },
  { name: "MS Excel", type: "Tools", regex: "excel" },
  { name: "MS Office", type: "Tools", regex: "(ms office|microsoft office)" },
  { name: "MS Word", type: "Tools", regex: "(ms word|microsoft word)" },
  { name: "MS PowerPoint", type: "Tools", regex: "power point" },
  { name: "JUnit", type: "Tools", regex: "junit" },
  { name: "LoadRunner", type: "Tools", regex: "load runner" },
  { name: "Lotus Notes", type: "Tools", regex: "lotus notes" },
  {
    name: "MS Project",
    type: "Tools",
    regex: "(ms project|microsoft project)",
  },
  { name: "Visio", type: "Tools", regex: "visio\\b" },
  { name: "mobius", type: "Tools", regex: "mobius" },
  { name: "NetBeans", type: "Tools", regex: "net beans" },
  { name: "QTP", type: "Tools", regex: "(qtp|quick test pro)" },
  { name: "ClearQuest", type: "Tools", regex: "clear quest\\b" },
  { name: "RUP", type: "Tools", regex: "(rup|rational unified process)" },
  { name: "SharePoint", type: "Tools", regex: "share point\\b}" },
  { name: "SharePoint Designer", type: "Tools", regex: "share point designer" },
  { name: "SQL*Developer", type: "Tools", regex: "sql\\*developer" },
  { name: "SQL*Plus", type: "Tools", regex: "sql\\*plus" },
  { name: "SSIS", type: "Tools", regex: "ssis" },
  { name: "SSRS", type: "Tools", regex: "ssrs" },
  { name: "SSAS", type: "Tools", regex: "ssas" },
  { name: "TFS", type: "Tools", regex: "(tfs|team foundation server)" },
  { name: "Git", type: "Tools", regex: "git" },
  { name: "Subversion", type: "Tools", regex: "subversion" },
  { name: "Tivoli", type: "Tools", regex: "tivoli" },
  { name: "TOAD", type: "Tools", regex: "toad" },
  { name: "Visual Studio", type: "Tools", regex: "visual studio" },
  { name: "VersionOne", type: "Tools", regex: "(version one|version1)" },
  { name: "VMware", type: "Tools", regex: "vm ware" },
  { name: "ESXi", type: "Tools", regex: "esx i" },
  { name: "Hyper-V", type: "Tools", regex: "(hyper v|hyper\\-v)" },
  { name: "Cisco", type: "Tools", regex: "cisco" },
  { name: "Sonicwall", type: "Tools", regex: "sonicwall" },
  { name: "Procurve", type: "Tools", regex: "procurve" },
  { name: "vCenter", type: "Tools", regex: "vcenter" },
  { name: "vSphere", type: "Tools", regex: "vsphere" },
  { name: "Avaya", type: "Tools", regex: "avaya" },
  { name: "Selenium", type: "Tools", regex: "selenium" },
  { name: "cucumber", type: "Tools", regex: "cucumber" },
  { name: "WinCVS", type: "Tools", regex: "wincvs" },
  { name: "winrunner", type: "Tools", regex: "winrunner" },
  { name: "WordPress", type: "Tools", regex: "wordpress" },
  { name: "Crystal Reports", type: "Tools", regex: "crystal reports" },
  { name: "Zimbra", type: "Tools", regex: "zimbra" },
  { name: "Eclipse", type: "Tools", regex: "eclipse\\b" },
  { name: "Jira", type: "Tools", regex: "jira\\b" },
];
